# Usage:
#
#    Build image:
#    docker build -t angular-starter .
#
#    Run image (on localhost:8080):
#    docker run --name angular-starter -p 8080:80 angular-starter
#
#    Run image as virtual host (read more: https://github.com/jwilder/nginx-proxy):
#    docker run -e VIRTUAL_HOST=angular-starter.your-domain.com --name angular-starter angular-starter

FROM node:8.9.4-alpine as builder

# Uncomment this if you encounter node-sass environment changed issue (1/2)
RUN apk add --no-cache python &&\
    apk add --no-cache g++

COPY package.json ./

## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
RUN npm i &&\
    mkdir /ng-app &&\
    mv ./node_modules ./ng-app

# Uncomment this if you encounter node-sass environment changed issue (2/2)
RUN npm rebuild node-sass --force

WORKDIR /ng-app

COPY . .
